alias ls="exa --git --group-directories-first --time-style=long-iso"
alias l="ls -1"
alias sl="ls"
alias ll="ls -al"
alias llm="ll --sort=modified"
alias la="ls -lbhHigUmuSa"
alias tree="exa --tree"
alias ip="ip --color=auto"
alias nrb="sudo nixos-rebuild"
alias ns="nix search --no-update-lock-file nixos"
